spring:
  datasource:
    url: jdbc:h2:mem:myDb:DB_CLOSE_DELAY=-1;MODE=MYSQL;INIT=CREATE SHCEMA IF NOT EXISTS
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
  jpa:
    show-sql: on
